// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppendAutoSave(arg1:string,arg2:string):Promise<string>;

export function AppendGoogleStream(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AppendLive(arg1:string):Promise<void>;

export function BeginAutoSave():Promise<string>;

export function CommitLive():Promise<void>;

export function EndAutoSave():Promise<string>;

export function EndGoogleStream(arg1:string,arg2:string):Promise<Array<string>>;

export function GetInfo():Promise<main.AppInfo>;

export function LogDiagnostic(arg1:string):Promise<void>;

export function SaveTranscript(arg1:string):Promise<boolean>;

export function SetAutoSave(arg1:boolean):Promise<void>;

export function SetDebugLogging(arg1:boolean):Promise<void>;

export function SetShowTimestamps(arg1:boolean):Promise<void>;

export function StartGoogleStream(arg1:string,arg2:string):Promise<void>;

export function StartLive():Promise<void>;

export function StopLive():Promise<void>;

export function Transcribe(arg1:string,arg2:string):Promise<main.Transcript>;
