// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendGoogleStream(arg1, arg2, arg3) {
  return window['go']['main']['App']['AppendGoogleStream'](arg1, arg2, arg3);
}

export function AppendLive(arg1) {
  return window['go']['main']['App']['AppendLive'](arg1);
}

export function BeginAutoSave() {
  return window['go']['main']['App']['BeginAutoSave']();
}

export function CommitLive() {
  return window['go']['main']['App']['CommitLive']();
}

export function EndAutoSave(arg1) {
  return window['go']['main']['App']['EndAutoSave'](arg1);
}

export function EndGoogleStream(arg1, arg2) {
  return window['go']['main']['App']['EndGoogleStream'](arg1, arg2);
}

export function GetInfo() {
  return window['go']['main']['App']['GetInfo']();
}

export function LogDiagnostic(arg1) {
  return window['go']['main']['App']['LogDiagnostic'](arg1);
}

export function SaveTranscript(arg1) {
  return window['go']['main']['App']['SaveTranscript'](arg1);
}

export function SetAutoSave(arg1) {
  return window['go']['main']['App']['SetAutoSave'](arg1);
}

export function SetDebugLogging(arg1) {
  return window['go']['main']['App']['SetDebugLogging'](arg1);
}

export function SetShowTimestamps(arg1) {
  return window['go']['main']['App']['SetShowTimestamps'](arg1);
}

export function StartGoogleStream(arg1, arg2) {
  return window['go']['main']['App']['StartGoogleStream'](arg1, arg2);
}

export function StartLive() {
  return window['go']['main']['App']['StartLive']();
}

export function StopLive() {
  return window['go']['main']['App']['StopLive']();
}

export function Transcribe(arg1, arg2) {
  return window['go']['main']['App']['Transcribe'](arg1, arg2);
}

export function WriteAutoSave(arg1) {
  return window['go']['main']['App']['WriteAutoSave'](arg1);
}
